# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: features.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='features.proto',
  package='rogers.sample',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x66\x65\x61tures.proto\x12\rrogers.sample\"\xae\x02\n\x07\x46\x65\x61ture\x12\x32\n\x04type\x18\x01 \x01(\x0e\x32$.rogers.sample.Feature.Variable.Type\x12\x32\n\x04mode\x18\x02 \x01(\x0e\x32$.rogers.sample.Feature.Modality.Type\x12#\n\x05value\x18\x03 \x01(\x0b\x32\x14.rogers.sample.Value\x1aN\n\x08Variable\"B\n\x04Type\x12\x0f\n\x0b\x43\x41TEGORICAL\x10\x00\x12\x0e\n\nCONTINUOUS\x10\x01\x12\x0c\n\x08\x44ISCRETE\x10\x02\x12\x0b\n\x07ORDINAL\x10\x03\x1a\x46\n\x08Modality\":\n\x04Type\x12\t\n\x05\x42YTES\x10\x00\x12\n\n\x06STATIC\x10\x01\x12\x0b\n\x07\x44YNAMIC\x10\x02\x12\x0e\n\nCONTEXTUAL\x10\x03\"\x8d\x01\n\x08\x46\x65\x61tures\x12\x0e\n\x06sha256\x18\x01 \x01(\t\x12-\n\x03map\x18\x02 \x03(\x0b\x32 .rogers.sample.Features.MapEntry\x1a\x42\n\x08MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.rogers.sample.Feature:\x02\x38\x01\"}\n\x06Struct\x12/\n\x05value\x18\x01 \x03(\x0b\x32 .rogers.sample.Struct.ValueEntry\x1a\x42\n\nValueEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.rogers.sample.Value:\x02\x38\x01\"+\n\x04List\x12#\n\x05value\x18\x01 \x03(\x0b\x32\x14.rogers.sample.Value\"\xcb\x01\n\x05Value\x12\x16\n\x0cstring_value\x18\x01 \x01(\tH\x00\x12\x14\n\nbool_value\x18\x02 \x01(\x08H\x00\x12\x13\n\tint_value\x18\x03 \x01(\x04H\x00\x12\x16\n\x0c\x64ouble_value\x18\x04 \x01(\x01H\x00\x12-\n\x0cstruct_value\x18\x05 \x01(\x0b\x32\x15.rogers.sample.StructH\x00\x12)\n\nlist_value\x18\x06 \x01(\x0b\x32\x13.rogers.sample.ListH\x00\x42\r\n\x0bvalue_oneofB\x02H\x01\x62\x06proto3')
)



_FEATURE_VARIABLE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='rogers.sample.Feature.Variable.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CATEGORICAL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTINUOUS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISCRETE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORDINAL', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=198,
  serialized_end=264,
)
_sym_db.RegisterEnumDescriptor(_FEATURE_VARIABLE_TYPE)

_FEATURE_MODALITY_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='rogers.sample.Feature.Modality.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BYTES', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATIC', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DYNAMIC', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTEXTUAL', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=278,
  serialized_end=336,
)
_sym_db.RegisterEnumDescriptor(_FEATURE_MODALITY_TYPE)


_FEATURE_VARIABLE = _descriptor.Descriptor(
  name='Variable',
  full_name='rogers.sample.Feature.Variable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FEATURE_VARIABLE_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=264,
)

_FEATURE_MODALITY = _descriptor.Descriptor(
  name='Modality',
  full_name='rogers.sample.Feature.Modality',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FEATURE_MODALITY_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=336,
)

_FEATURE = _descriptor.Descriptor(
  name='Feature',
  full_name='rogers.sample.Feature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='rogers.sample.Feature.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mode', full_name='rogers.sample.Feature.mode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='rogers.sample.Feature.value', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_FEATURE_VARIABLE, _FEATURE_MODALITY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=336,
)


_FEATURES_MAPENTRY = _descriptor.Descriptor(
  name='MapEntry',
  full_name='rogers.sample.Features.MapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='rogers.sample.Features.MapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='rogers.sample.Features.MapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=480,
)

_FEATURES = _descriptor.Descriptor(
  name='Features',
  full_name='rogers.sample.Features',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sha256', full_name='rogers.sample.Features.sha256', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='map', full_name='rogers.sample.Features.map', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_FEATURES_MAPENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=480,
)


_STRUCT_VALUEENTRY = _descriptor.Descriptor(
  name='ValueEntry',
  full_name='rogers.sample.Struct.ValueEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='rogers.sample.Struct.ValueEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='rogers.sample.Struct.ValueEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=607,
)

_STRUCT = _descriptor.Descriptor(
  name='Struct',
  full_name='rogers.sample.Struct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='rogers.sample.Struct.value', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_STRUCT_VALUEENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=482,
  serialized_end=607,
)


_LIST = _descriptor.Descriptor(
  name='List',
  full_name='rogers.sample.List',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='rogers.sample.List.value', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=609,
  serialized_end=652,
)


_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='rogers.sample.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='string_value', full_name='rogers.sample.Value.string_value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bool_value', full_name='rogers.sample.Value.bool_value', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int_value', full_name='rogers.sample.Value.int_value', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='double_value', full_name='rogers.sample.Value.double_value', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='struct_value', full_name='rogers.sample.Value.struct_value', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='list_value', full_name='rogers.sample.Value.list_value', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value_oneof', full_name='rogers.sample.Value.value_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=655,
  serialized_end=858,
)

_FEATURE_VARIABLE.containing_type = _FEATURE
_FEATURE_VARIABLE_TYPE.containing_type = _FEATURE_VARIABLE
_FEATURE_MODALITY.containing_type = _FEATURE
_FEATURE_MODALITY_TYPE.containing_type = _FEATURE_MODALITY
_FEATURE.fields_by_name['type'].enum_type = _FEATURE_VARIABLE_TYPE
_FEATURE.fields_by_name['mode'].enum_type = _FEATURE_MODALITY_TYPE
_FEATURE.fields_by_name['value'].message_type = _VALUE
_FEATURES_MAPENTRY.fields_by_name['value'].message_type = _FEATURE
_FEATURES_MAPENTRY.containing_type = _FEATURES
_FEATURES.fields_by_name['map'].message_type = _FEATURES_MAPENTRY
_STRUCT_VALUEENTRY.fields_by_name['value'].message_type = _VALUE
_STRUCT_VALUEENTRY.containing_type = _STRUCT
_STRUCT.fields_by_name['value'].message_type = _STRUCT_VALUEENTRY
_LIST.fields_by_name['value'].message_type = _VALUE
_VALUE.fields_by_name['struct_value'].message_type = _STRUCT
_VALUE.fields_by_name['list_value'].message_type = _LIST
_VALUE.oneofs_by_name['value_oneof'].fields.append(
  _VALUE.fields_by_name['string_value'])
_VALUE.fields_by_name['string_value'].containing_oneof = _VALUE.oneofs_by_name['value_oneof']
_VALUE.oneofs_by_name['value_oneof'].fields.append(
  _VALUE.fields_by_name['bool_value'])
_VALUE.fields_by_name['bool_value'].containing_oneof = _VALUE.oneofs_by_name['value_oneof']
_VALUE.oneofs_by_name['value_oneof'].fields.append(
  _VALUE.fields_by_name['int_value'])
_VALUE.fields_by_name['int_value'].containing_oneof = _VALUE.oneofs_by_name['value_oneof']
_VALUE.oneofs_by_name['value_oneof'].fields.append(
  _VALUE.fields_by_name['double_value'])
_VALUE.fields_by_name['double_value'].containing_oneof = _VALUE.oneofs_by_name['value_oneof']
_VALUE.oneofs_by_name['value_oneof'].fields.append(
  _VALUE.fields_by_name['struct_value'])
_VALUE.fields_by_name['struct_value'].containing_oneof = _VALUE.oneofs_by_name['value_oneof']
_VALUE.oneofs_by_name['value_oneof'].fields.append(
  _VALUE.fields_by_name['list_value'])
_VALUE.fields_by_name['list_value'].containing_oneof = _VALUE.oneofs_by_name['value_oneof']
DESCRIPTOR.message_types_by_name['Feature'] = _FEATURE
DESCRIPTOR.message_types_by_name['Features'] = _FEATURES
DESCRIPTOR.message_types_by_name['Struct'] = _STRUCT
DESCRIPTOR.message_types_by_name['List'] = _LIST
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Feature = _reflection.GeneratedProtocolMessageType('Feature', (_message.Message,), dict(

  Variable = _reflection.GeneratedProtocolMessageType('Variable', (_message.Message,), dict(
    DESCRIPTOR = _FEATURE_VARIABLE,
    __module__ = 'features_pb2'
    # @@protoc_insertion_point(class_scope:rogers.sample.Feature.Variable)
    ))
  ,

  Modality = _reflection.GeneratedProtocolMessageType('Modality', (_message.Message,), dict(
    DESCRIPTOR = _FEATURE_MODALITY,
    __module__ = 'features_pb2'
    # @@protoc_insertion_point(class_scope:rogers.sample.Feature.Modality)
    ))
  ,
  DESCRIPTOR = _FEATURE,
  __module__ = 'features_pb2'
  # @@protoc_insertion_point(class_scope:rogers.sample.Feature)
  ))
_sym_db.RegisterMessage(Feature)
_sym_db.RegisterMessage(Feature.Variable)
_sym_db.RegisterMessage(Feature.Modality)

Features = _reflection.GeneratedProtocolMessageType('Features', (_message.Message,), dict(

  MapEntry = _reflection.GeneratedProtocolMessageType('MapEntry', (_message.Message,), dict(
    DESCRIPTOR = _FEATURES_MAPENTRY,
    __module__ = 'features_pb2'
    # @@protoc_insertion_point(class_scope:rogers.sample.Features.MapEntry)
    ))
  ,
  DESCRIPTOR = _FEATURES,
  __module__ = 'features_pb2'
  # @@protoc_insertion_point(class_scope:rogers.sample.Features)
  ))
_sym_db.RegisterMessage(Features)
_sym_db.RegisterMessage(Features.MapEntry)

Struct = _reflection.GeneratedProtocolMessageType('Struct', (_message.Message,), dict(

  ValueEntry = _reflection.GeneratedProtocolMessageType('ValueEntry', (_message.Message,), dict(
    DESCRIPTOR = _STRUCT_VALUEENTRY,
    __module__ = 'features_pb2'
    # @@protoc_insertion_point(class_scope:rogers.sample.Struct.ValueEntry)
    ))
  ,
  DESCRIPTOR = _STRUCT,
  __module__ = 'features_pb2'
  # @@protoc_insertion_point(class_scope:rogers.sample.Struct)
  ))
_sym_db.RegisterMessage(Struct)
_sym_db.RegisterMessage(Struct.ValueEntry)

List = _reflection.GeneratedProtocolMessageType('List', (_message.Message,), dict(
  DESCRIPTOR = _LIST,
  __module__ = 'features_pb2'
  # @@protoc_insertion_point(class_scope:rogers.sample.List)
  ))
_sym_db.RegisterMessage(List)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), dict(
  DESCRIPTOR = _VALUE,
  __module__ = 'features_pb2'
  # @@protoc_insertion_point(class_scope:rogers.sample.Value)
  ))
_sym_db.RegisterMessage(Value)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\001'))
_FEATURES_MAPENTRY.has_options = True
_FEATURES_MAPENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_STRUCT_VALUEENTRY.has_options = True
_STRUCT_VALUEENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
